WITH tmp_table AS (SELECT 
    COALESCE(t1.record_id, t2.record_id) AS record_id,  -- Use madrs_record_id if available, else phq9_record_id
    t1.record_id AS madrs_record_id,
    t2.record_id AS phq9_record_id,
    t1.baseline_date AS madrs_baseline_date,
    t1.baseline_score AS madrs_baseline_score,
    t1.week10_date AS madrs_week10_date,
    t1.week10_score AS madrs_week10_score,
    t2.baseline_date AS phq9_baseline_date,
    t2.week2_date AS phq9_week2_date,
    t2.week2_score AS phq9_week2_score,
    t2.week4_date AS phq9_week4_date,
    t2.week4_score AS phq9_week4_score,
    t2.week6_date AS phq9_week6_date,
    t2.week6_score AS phq9_week6_score,
    t2.week8_date AS phq9_week8_date,
    t2.week8_score AS phq9_week8_score,
    t2.week10_date AS phq9_week10_date,
    t2.week10_score AS phq9_week10_score
FROM baard.madrs_af t1
LEFT JOIN baard.phq9_af t2 ON t1.record_id = t2.record_id

UNION

SELECT 
    COALESCE(t1.record_id, t2.record_id) AS record_id,  -- Use madrs_record_id if available, else phq9_record_id
    t1.record_id AS madrs_record_id,
    t2.record_id AS phq9_record_id,
    t1.baseline_date AS madrs_baseline_date,
    t1.baseline_score AS madrs_baseline_score,
    t1.week10_date AS madrs_week10_date,
    t1.week10_score AS madrs_week10_score,
    t2.baseline_date AS phq9_baseline_date,
    t2.week2_date AS phq9_week2_date,
    t2.week2_score AS phq9_week2_score,
    t2.week4_date AS phq9_week4_date,
    t2.week4_score AS phq9_week4_score,
    t2.week6_date AS phq9_week6_date,
    t2.week6_score AS phq9_week6_score,
    t2.week8_date AS phq9_week8_date,
    t2.week8_score AS phq9_week8_score,
    t2.week10_date AS phq9_week10_date,
    t2.week10_score AS phq9_week10_score
FROM baard.madrs_af t1
RIGHT JOIN baard.phq9_af t2 ON t1.record_id = t2.record_id)
SELECT 
	COALESCE(t3.record_id, t4.record_id) AS record_id,  -- Use madrs_record_id if available, else phq9_record_id
    t3.madrs_record_id,
    t3.phq9_record_id,
    t4.record_id AS med_record_id,
    t3.madrs_baseline_date,
    t3.madrs_baseline_score,
    t3.madrs_week10_date,
    t3.madrs_week10_score,
    t3.phq9_baseline_date,
    t3.phq9_week2_date,
    t3.phq9_week2_score,
    t3.phq9_week4_date,
    t3.phq9_week4_score,
    t3.phq9_week6_date,
    t3.phq9_week6_score,
    t3.phq9_week8_date,
    t3.phq9_week8_score,
    t3.phq9_week10_date,
    t3.phq9_week10_score,
    DATE_FORMAT(STR_TO_DATE(t4.week2_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week2_decision_date,
    t4.week2_med1,
    t4.week2_med1_freq,
    t4.week2_med2,
    t4.week2_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week4_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week4_decision_date,
    t4.week4_med1,
    t4.week4_med1_freq,
    t4.week4_med2,
    t4.week4_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week6_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week6_decision_date,
    t4.week6_med1,
    t4.week6_med1_freq,
    t4.week6_med2,
    t4.week6_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week8_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week8_decision_date,
    t4.week8_med1,
    t4.week8_med1_freq,
    t4.week8_med2,
    t4.week8_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week10_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week10_decision_date,
    t4.week10_med1,
    t4.week10_med1_freq,
    t4.week10_med2,
    t4.week10_med2_freq
	FROM tmp_table t3
  LEFT JOIN baard.medication_af t4
     ON	t3.record_id = t4.record_id
  UNION
  SELECT 
	COALESCE(t3.record_id, t4.record_id) AS record_id,  -- Use madrs_record_id if available, else phq9_record_id
    t3.madrs_record_id,
    t3.phq9_record_id,
    t4.record_id AS med_record_id,
    t3.madrs_baseline_date,
    t3.madrs_baseline_score,
    t3.madrs_week10_date,
    t3.madrs_week10_score,
    t3.phq9_baseline_date,
    t3.phq9_week2_date,
    t3.phq9_week2_score,
    t3.phq9_week4_date,
    t3.phq9_week4_score,
    t3.phq9_week6_date,
    t3.phq9_week6_score,
    t3.phq9_week8_date,
    t3.phq9_week8_score,
    t3.phq9_week10_date,
    t3.phq9_week10_score,
    DATE_FORMAT(STR_TO_DATE(t4.week2_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week2_decision_date,
    t4.week2_med1,
    t4.week2_med1_freq,
    t4.week2_med2,
    t4.week2_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week4_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week4_decision_date,
    t4.week4_med1,
    t4.week4_med1_freq,
    t4.week4_med2,
    t4.week4_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week6_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week6_decision_date,
    t4.week6_med1,
    t4.week6_med1_freq,
    t4.week6_med2,
    t4.week6_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week8_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week8_decision_date,
    t4.week8_med1,
    t4.week8_med1_freq,
    t4.week8_med2,
    t4.week8_med2_freq,
    DATE_FORMAT(STR_TO_DATE(t4.week10_decision_date, '%m/%d/%Y'), '%Y-%m-%d') AS week10_decision_date,
    t4.week10_med1,
    t4.week10_med1_freq,
    t4.week10_med2,
    t4.week10_med2_freq
     FROM tmp_table t3 
 RIGHT JOIN baard.medication_af t4
     ON t3.record_id = t4.record_id;
